### PR TITLE
Adding Yechiel

### PR DESCRIPTION
**Pull request by achasveachas**
### Who are you and what do you do now?
My name is Yechiel Kalmenson.
I also go by [Rabbi On Rails](https://blog.yechiel.me) even though I do PHP for a living.

### What was/were your previous career(s)?
Rabbi, Teacher, and Tech Support.

### What aspects of your story do you want to share with the Second Career Devs audience?
How my training as a rabbi taught me to appreciate the moral and ethical aspects of my development job.
How my job as a teacher gave me an appreciation of the joys of teaching and mentoring those who may be behind me and don't know as much as I do now. 
And how my job in tech support gave me the perspective and empathy needed to develop with the (often non-technical) end user in mind.

### CODE REVIEW

**Comment by kyleshevlin** [comment]
Hi Yechiel, thanks for submitting your name for the podcast! I like your story. Currently, this PR has some conflicts and can't be automatically merged. Here's what I'd love to do.

I like the idea you had to make all the Twitter handles links, but I'd like to handle that in a separate PR. Do you mind cherry picking just `e2a8f7c` and only submitting your name addition?

Once that's merged if you'd like to turn the handles into links that would be fine to submit to in a separate PR. Although I wouldn't change `@swyx`'s first name. It's what he submitted and perhaps that's how he wanted it to be.

**Comment by achasveachas** [comment]
Sure @kyleshevlin, I removed the other commits, you can go ahead and merge them now.

`@swyx`'s name was an accident (I did a find/replace to turn all the `@*` into links and because his name was `@swyx` it got updated along with everything else.

**Comment by achasveachas** [comment]
Sorry about that, it's done now. It looks like the only conflict is from a commit that was made after I forked.

**Review by kyleshevlin — APPROVED** [review]
LGTM!

**Pull request merged**
